cache = true
max_cache_age = "30 days"

max_retries = 5
retry_wait_time = 30 # seconds

exclude = [
  # 无需检查
  '^https://github\.com/BITNP/BIThesis-wiki/edit/main/',
  '^file://.*/\.vitepress/dist/assets/.+\.(css|js|woff2)',

  # 经常被屏蔽或访问不到
  '^https://(grd|jwb|mirrors|cs|mirror)\.bit\.edu\.cn',
  '^https://tex\.stackexchange\.com',
  '^https://www\.tablesgenerator\.com',
  '^https://.+\.zhihu\.com',
  # 已坏，但仅用于 URL 示例
  '^https://www\.cnnic\.net\.cn/hlwfzyj/hlwxzbg/201201/P020120709345264469680',
  # 经常超时或 403 Forbidden
  '^https://www\.adobe\.com/acrobat/online',
]
