cache = true
max_cache_age = "30 days"

max_retries = 5
retry_wait_time = 30 # seconds

exclude = [
  '^https://(grd|jwb|mirrors|cs)\.bit\.edu\.cn',
  '^https://tex\.stackexchange\.com',
  '^https://www\.tablesgenerator\.com',
  '^https://.+\.zhihu\.com',
  '^https://www\.cnnic\.net\.cn/hlwfzyj/hlwxzbg/201201/P020120709345264469680',
]
